// sample data
const clientData = {
  client: {
    person: {
      id: 52,
      client_code: "CHL89",
      client_name: "Leshinsky, Chanah",
      last_name: "Leshinsky",
      first_name: "Chanah",
      middle_name: "",
      dob: "1989-01-05",
      ssn: "184705994",
      mmn: "Fiderer",
      email: "chanileshinsky@gmail.com",
      pwd: "025336219rt",
      occupation: "Teacher",
      employer: "Self",
      income: 60000.0,
      phone: "8454592067",
      phone_2: "",
      contact_email: "chanie3132@gmail.com",
      tax_status: "",
      wise: false,
      client_status: "ACTIVE",
      notes: "",
      client_info: null,
    },
    credit_summary: {
      id: 52,
      client_code: "CHL89",
      client_name: "Leshinsky, Chanah",
      cc_account_count: 9,
      loan_count: 0,
      checking_count: 0,
      email: "chanileshinsky@gmail.com",
      phone: "8454592067",
      min_open_date: "2022-01-14",
      total_credit_limit: 48300.0,
      credit_limit: 0.0,
    },
    addresses: [
      {
        id: 70,
        client_id: 52,
        client_code: "CHL89",
        street_address: "2 Monroe Ln",
        city: "Jackson",
        state: "NJ",
        zip: "08527",
        is_current: true,
        recorded_on: "2023-01-05T23:35:53.925Z",
      },
      {
        id: 175,
        client_id: 79,
        client_code: "DAO58",
        street_address: "4109 Legation Street",
        city: "Denver",
        state: "WY",
        zip: "92453",
        is_current: false,
        recorded_on: "2023-01-08T00:02:52.246Z",
      },
    ],
    client_israels: [
      {
        id: 42,
        client_id: 52,
        client_code: "CHL89",
        bank: "PAGI",
        branch: "185",
        account: "510718",
        iban: null,
        iban_name: "Shlomo Itzhak and Chana Leshinsky",
        address: "9 Nahal Arugot",
        city: "Bet Shemesh",
        zip: "9909708",
        phone: "054-849-2946",
        notes: "",
        recorded_on: "2023-01-03T23:05:13.667Z",
      },
    ],
    cc_accounts: [
      {
        id: 14,
        client_id: 52,
        client_name: "Leshinsky,Chanah",
        xero_id: "CTD-CHL89",
        client_code: "CHL89",
        first_name: "Chanah",
        last_name: "Leshinsky",
        card_name: "Citi Diamond",
        card_status: "ACTIVE",
        cc_status_desc: "Active, Earning Points",
        device: "",
        device_desc: "",
        open_date: null,
        cc_login: "cleshinsky2",
        cc_pwd: "September9!",
        cc_card_info: null,
        reconciled_on: "2022-10-25",
        charged_on: "2022-09-20",
        credit_line: 800.0,
        due_on: null,
        bonus_to_spend: null,
        bonus_spend_by: null,
        bonus_spent: null,
        ccaccount_info: null,
        task: null,
        in_charge: "Tzivia",
        notes: "",
        recorded_on: "2023-01-03T22:42:15.812Z",
        card_num: "1234123456785678",
        card_exp: "0327",
        card_cvv: "348",
        card_pin: "7070",
      },
      {
        id: 15,
        client_id: 52,
        client_name: "Leshinsky,Chanah",
        xero_id: "CTP-CHL89",
        client_code: "CHL89",
        first_name: "Chanah",
        last_name: "Leshinsky",
        card_name: "Citi Premier",
        card_status: "ACTIVE",
        cc_status_desc: "Active, Earning Points",
        device: "",
        device_desc: "",
        open_date: null,
        cc_login: "cleshinsky2",
        cc_pwd: "September9!",
        cc_card_info: null,
        reconciled_on: "2022-10-25",
        charged_on: "2022-09-20",
        credit_line: 2000.0,
        due_on: null,
        bonus_to_spend: null,
        bonus_spend_by: null,
        bonus_spent: null,
        ccaccount_info: null,
        task: null,
        in_charge: "Tzivia",
        notes: "",
        recorded_on: "2023-01-03T22:42:15.815Z",
        card_num: "9876987654325432",
        card_exp: "0428",
        card_cvv: "254",
        card_pin: "2034",
      },
      {
        id: 96,
        client_id: 52,
        client_name: "Leshinsky,Chanah",
        xero_id: "SYL-CHL89",
        client_code: "CHL89",
        first_name: "Chanah",
        last_name: "Leshinsky",
        card_name: "Synchrony Lowe's",
        card_status: "ACTIVE",
        cc_status_desc: "Active, Earning Points",
        device: "",
        device_desc: "",
        open_date: null,
        cc_login: "cleshinsky2",
        cc_pwd: "London2!",
        cc_card_info: null,
        reconciled_on: "2022-11-06",
        charged_on: "2022-10-07",
        credit_line: 12000.0,
        due_on: null,
        bonus_to_spend: null,
        bonus_spend_by: null,
        bonus_spent: null,
        ccaccount_info: null,
        task: null,
        in_charge: "Tzivia",
        notes: "",
        recorded_on: "2023-01-03T22:42:16.129Z",
        card_num: null,
        card_exp: null,
        card_cvv: null,
        card_pin: null,
      },
      {
        id: 104,
        client_id: 52,
        client_name: "Leshinsky,Chanah",
        xero_id: "SYM-CHL89",
        client_code: "CHL89",
        first_name: "Chanah",
        last_name: "Leshinsky",
        card_name: "Synchrony MC",
        card_status: "ACTIVE",
        cc_status_desc: "Active, Earning Points",
        device: "",
        device_desc: "",
        open_date: null,
        cc_login: "cleshinsky2",
        cc_pwd: "London2!",
        cc_card_info: null,
        reconciled_on: "2022-11-06",
        charged_on: "2022-10-07",
        credit_line: 10000.0,
        due_on: null,
        bonus_to_spend: null,
        bonus_spend_by: null,
        bonus_spent: null,
        ccaccount_info: null,
        task: null,
        in_charge: "Tzivia",
        notes: "",
        recorded_on: "2023-01-03T22:42:16.161Z",
        card_num: null,
        card_exp: null,
        card_cvv: null,
        card_pin: null,
      },
      {
        id: 143,
        client_id: 52,
        client_name: "Leshinsky,Chanah",
        xero_id: "BCAB-CHL89",
        client_code: "CHL89",
        first_name: "Chanah",
        last_name: "Leshinsky",
        card_name: "Barclays AA B",
        card_status: "ACTIVE",
        cc_status_desc: "Active, Earning Points",
        device: "",
        device_desc: "",
        open_date: null,
        cc_login: "cleshinsky2",
        cc_pwd: "London2!",
        cc_card_info: null,
        reconciled_on: "2022-11-07",
        charged_on: "2022-10-30",
        credit_line: 2500.0,
        due_on: null,
        bonus_to_spend: null,
        bonus_spend_by: null,
        bonus_spent: null,
        ccaccount_info: null,
        task: null,
        in_charge: "Tzivia",
        notes: "",
        recorded_on: "2023-01-03T22:42:16.295Z",
        card_num: "1357246813572357",
        card_exp: "1223",
        card_cvv: "909",
      },
    ],
    loans: [
      {
        id: 40,
        client_id: 79,
        xero_id: "34.DAO58",
        client_code: "DAO58",
        first_name: "Daniel",
        last_name: "Ostroff",
        card_name: "Chase",
        loan_status: "POTENTIAL",
        device: "iPad Safari",
        open_date: "2010-08-10T00:00:00.000",
        login: "dmostroff",
        pwd: "1234",
        loan_number: "12345",
        reconciled_on: "2004-09-24T00:00:00.000",
        credit_line: 23444.0,
        autopay_account: "Heart",
        due_on: "2023-01-15T00:00:00.000",
        loan_type: null,
        maturity_on: "1963-11-22T00:00:00.000",
        loan_info: "toto",
        task: "phone",
        notes: "private",
        recorded_on: "2023-01-13T00:44:36.721Z",
      },
    ],
    credit_reports: [
      {
        id: 56,
        client_id: 52,
        client_code: "CHL89",
        credit_bureau: "Experian",
        login: "chanileshinsky@gmail.com",
        pwd: "7326643993Rt",
        pin: "",
        recorded_on: "2023-01-03T23:00:45.451Z",
      },
    ],
    checkings: [
      {
        id: 8,
        client_id: 79,
        xero_id: "1.WF-DAO58",
        xero_main: false,
        client_code: "DAO58",
        client_code_additional: null,
        name_on_account: "Daniel Ostroff",
        account_status: "OPENING",
        device: "Red Chrome",
        open_date: null,
        login: "dmostroff2",
        pwd: "September16@",
        bank: "Wells Fargo",
        routing: "021200025",
        account: "392626 9675",
        member_number: "392626 9675",
        debit_card_info: "4737 0240 4067 7447~09/23~984~6219",
        phone_pin: null,
        reconciled_on: "2014-07-20T00:00:00.000",
        zelle: "ostroff2015@gmail",
        wise: false,
        wise_device: null,
        checking_info: null,
        task: null,
        notes: "you interrupt when I talk",
        recorded_on: "2023-01-03T22:42:11.259Z",
        debit_card_num: "4737 0240 4067 7447",
        debit_card_exp: "09/23",
        debit_card_cvv: "984",
        debit_card_pin: "6219",
      },
      {
        id: 18,
        client_id: 79,
        xero_id: "1.PF-DAO58",
        xero_main: false,
        client_code: "DAO58",
        client_code_additional: null,
        name_on_account: "Daniel Ostroff",
        account_status: "ACTIVE",
        device: "Purple App",
        open_date: null,
        login: "dmostroff2",
        pwd: "February11",
        bank: "PenFed",
        routing: "256078446",
        account: "593338 5014",
        member_number: "593338 5014",
        debit_card_info: "23323 445 6654 5675~12/13~455~5687",
        phone_pin: null,
        reconciled_on: null,
        zelle: "t@t.g.com",
        wise: false,
        wise_device: null,
        checking_info: null,
        task: null,
        notes: null,
        recorded_on: "2023-01-03T22:42:11.305Z",
        debit_card_num: "23323 445 6654 5675",
        debit_card_exp: "12/13",
        debit_card_cvv: "455",
        debit_card_pin: "5687",
      },
    ],
    credit_line_histories: [],
  },
};

export { clientData };
